
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/Header/Header";
import React from "react";

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const titles = await prisma.l76aj_content.findMany({
    select: {
      title: true,
    },
  });

  const titlesArray: string[] = titles.map(titleObj => titleObj.title);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header titles={titlesArray}/>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
