
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./components/Header/Header";
import React from "react";
import { datasList } from "@/app/utils/types";

import prisma from "./utils/prisma";

// import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const MainCategories = await prisma.main_categories.findMany({
    select: {
      category_name: true,
    },
  });

  const MainCategoriesArray: string[] = MainCategories.map(
    (titleObj: { category_name: string }) => titleObj.category_name
  );

  // const SubCategories = await prisma.sub_categories.findMany({
  //   where: {
  //     category_id: 1,
  //   },
  //   select: {
  //     sub_category_name: true,
  //   },
  // });

  // const SubCategoriesArray: string[] = SubCategories.map(
  //   (titleObj: { sub_category_name: string }) => titleObj.sub_category_name
  // );

  const categoryData = await prisma.main_categories.findUnique({
    where: { category_id: 1 }, // Remplacez 1 par l'identifiant de la catégorie principale souhaitée
    include: {
      sub_categories: {
        include: {
          titles: true,
        },
      },
    },
  });

  const datas : datasList = {
    mainCategories: MainCategoriesArray,
    categoryData: categoryData,
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header {...datas}/>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
